version: '3.7'
services:

# -----------------------------------------------------------------
# Banco de Dados:

  mysql_suitecrm:
    image: mysql:8.0
    restart: unless-stopped
    container_name: 'mysql_suitecrm'

    volumes:
      # Configuration
      # - ../config/mysql_suitecrm/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      # - ../config/mysql_suitecrm/config-file.cnf:/etc/mysql/config-file.cnf:ro
      # - ../config/mysql_suitecrm/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

      # data Storage
      - ./data/mysql_suitecrm:/var/lib/mysql

    command:
       - --default-authentication-plugin=mysql_native_password
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_general_ci
       - --disable-log-bin

    environment:
      MYSQL_ROOT_PASSWORD: 'Muito!!!Obrigado!!!Muito!!!Obrigado!!!Muito!!!Obrigado!!!'
      MYSQL_DATABASE: 'mysql_suitecrm'
      MYSQL_USER: 'mysql_suitecrm'
      MYSQL_PASSWORD: 'Muito!!!Obrigado!!!'

# -----------------------------------------------------------------
# Banco de Dados:

  suitecrm:
    image: 'bitnami/suitecrm:latest'
    restart: unless-stopped
    container_name: 'mysql_suitecrm'

    environment:
      MYSQL_CLIENT_FLAVOR: mysql
      SUITECRM_DATABASE_HOST: 'mysql_suitecrm'
      SUITECRM_DATABASE_PORT_NUMBER: '3306'
      SUITECRM_DATABASE_USER: 'mysql_suitecrm'
      SUITECRM_DATABASE_NAME: 'mysql_suitecrm'
      SUITECRM_DATABASE_PASSWORD: 'Muito!!!Obrigado!!!'

    volumes:
      - ./data/suitecrm:/bitnami
    depends_on:
      - mysql_suitecrm
